apiVersion: ahora.io/v1
kind: SPA
metadata:
  name: logcross
  namespace: logcross
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
spec:
  SPAArchiveURL: https://storage.googleapis.com/alster-crosswords/crosswords-1.0.9.tar.tz
  replicas: 1
  hosts: 
  - logcross.alster.co.il
  livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 3
    periodSeconds: 3
  readinessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 3
    periodSeconds: 3
  resources:
    requests:
      memory: "32Mi"
      cpu: "50m"
    limits:
      memory: "64Mi"
      cpu: "100m"
  paths:
  - path: /api
    pathType: Prefix
    backend:
      service:
        name: crosswords-api
        port:
          number: 80
