apiVersion: ahora.io.ahora.io/v1
kind: SPA
metadata:
  name: logcross
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  SPAArchiveURL: https://storage.googleapis.com/alster-crosswords/crosswords-0.0.5.tar.tz
  replicas: 1
  hosts: 
  - logcrossspa.alster.co.il
  livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 3
    periodSeconds: 3
  readinessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 3
    periodSeconds: 3
  resources:
    requests:
      memory: "32Mi"
      cpu: "50m"
    limits:
      memory: "64Mi"
      cpu: "100m"
  paths:
  - path: /api
    backend:
      serviceName: crosswords-api
      servicePort: 80
