apiVersion: ahora.ahora.dev/v1
kind: SPA
metadata:
  name: logcross
  namespace: logcross
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
spec:
  SPAArchiveURL: https://storage.googleapis.com/alster-crosswords/crosswords-1.0.9.tar.tz
  replicas: 1
  hosts: 
  - logcross.alster.co.il
  paths:
  - path: /api
    pathType: Prefix
    backend:
      service:
        name: crosswords-api
        port:
          number: 80
