apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: home.alster.control.dev-euw3.ecp-rnd.cqloud.com:6443
    token: jho59x.x9n511u9lfvtqug1
    unsafeSkipCAVerification: true
nodeRegistration:
  name: "k8s"
  criSocket: "unix:///run/cri-dockerd.sock"